[tool.mypy]
force_uppercase_builtins = true
strict = true

[tool.ruff]
extend-exclude = ["static", "ci/templates"]
line-length = 95
src = ["src", "tests"]
target-version = "py311"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
ignore = [
  "D203",  # pydocstyle one-blank-line-before-class
  "D213",  # pydocstyle multi-line-summary-second-line
  "D413",  # pydocstyle missing blank line after last section
  "RUF001",  # ruff-specific rules ambiguous-unicode-character-string
  "S101",  # flake8-bandit assert
  "S308",  # flake8-bandit suspicious-mark-safe-usage
  "E501"  # pycodestyle line-too-long
]
select = [
  "ANN",  # flake8-annotations (mypy type hinting)
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "D",  # pydocstyle
  "DTZ",  # flake8-datetimez
  "E",  # pycodestyle errors
  "EM",  # flake8-errmsg
  "EXE",  # flake8-executable
  "F",  # pyflakes
  "I",  # isort
  "INT",  # flake8-gettext
  "PERF",  # perflint
  "PIE",  # flake8-pie
  "PLC",  # pylint convention
  "PLE",  # pylint errors
  "PT",  # flake8-pytest-style
  "PTH",  # flake8-use-pathlib
  "Q",  # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # ruff-specific rules
  "S",  # flake8-bandit
  "SLF",  # flake8-self
  "SIM",  # flake8-simplify
  "UP",  # pyupgrade
  "W"  # pycodestyle warnings
]

[tool.ruff.lint.extend-per-file-ignores]
# Also ignore `D104` and `E402` in all `__init__.py` files.
"__init__.py" = ["D104", "E402"]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.isort]
force-single-line = true
forced-separate = ["conftest"]

[tool.ruff.lint.per-file-ignores]
"ci/*" = ["S", "D103", "ANN201"]
"tests/*" = ["SLF001", "ANN002", "ANN003"]
